### ISSUE TITLE
[Epic] Take down Research Ceph Cluster

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/epics#52]
# Motivation
To free up the nodes that the research ceph cluster is on. This will facilitate our move to upgrade much of our hardware.

# Completion criteria

- [x] https://github.com/CCI-MOC/ops-issues/issues/978
- [x] https://github.com/CCI-MOC/ops-issues/issues/979
- [x] https://github.com/CCI-MOC/ops-issues/issues/980

# Description
To allow for the hardware moves that we are working on the Research Ceph cluster must be taken down. We will need to create a pool in the production Ceph cluster, communicate with the current users to migrate, and finally shut down the research Ceph cluster.

# References
1. [epic](https://app.zenhub.com/workspaces/moc-alliance-backlog-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTQwMTUw)

# Changelog
2023-06-16: add epic link
