### ISSUE TITLE
[Epic] Process Donation of Servers from 2Sig

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/epics#55]
# Motivation
keep track of donated gear from 2 Sigma

# Completion criteria
all Nodes sent to Flax or utilized for internal projects

# Description

- [ ] get an idea of what was donated by spot-checking service tags in [this](https://docs.google.com/spreadsheets/d/1WkVlHszMLPzIGOs2VV8nyJKn_GJdrQQG/edit#gid=1365252970) sheet.
- [ ] send all nodes to Flax to save space in the MGHPCC
- [ ] have Flax return some of the Nodes for a ceph cluster

# References
1. [epic](https://app.zenhub.com/workspaces/moc-alliance-backlog-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTQ1Njk4)

# Changelog
2023-08-01: update epic link
