### ISSUE TITLE
[Epic] Bring up FX2 Rack 4

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/epics#71]
# Motivation
Adding to initial production ESI pool deployment as well as to increase NERC OCP hardware capacity.

# Completion criteria
1 rack of FX2s with FC830s & FC430s ready for use on NERC

# Description
Assuming it does not go above power or heat constraints this rack will be:
24x FC830
56x FC430

## Steps
- [ ] Connect Uplinks to TORS
- [ ] Provision TORS
- [ ] Confirm able to reach IPMI on all nodes in the cabinet
- [ ] Add nodes to ESI pool
- [ ] Location - Wayne (Chris Hill or Greg S)
- [ ] Power cables - Flax
- [ ] 25 G NICs added to FC830s - Flax
- [ ] Havard networking 200G or 400G connection between Harvard and MOC space

# References
1. [ZH Epic](https://app.zenhub.com/workspaces/moc-alliance-backlog-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTUwMjM5)

# Changelog
2023-08-29: add ZH Epic link
