### ISSUE TITLE
[Epic] Hypershift Testing

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/epics#73]
# Motivation
Review the potential of Hypershift for deploying clusters.

# Completion criteria
Confirm if Hypershift makes deploying OpenShift easier. Write up how-to steps.

# Description
- [x] nerc-project/operations#204
- [x] nerc-project/operations#206
- [x] nerc-project/operations#213
- [x] nerc-project/operations#207
- [ ] nerc-project/operations#208
- [x] nerc-project/operations#209
- [x] nerc-project/operations#210
- [x] nerc-project/operations#211

# References
1. [ZH Epic](https://github.com/nerc-project/operations#workspaces/moc-alliance-backlog-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTUxMzE1)

# Changelog
2023-08-29: add ZH Epic link
