### ISSUE TITLE
[Epic] Create a chart to help provide an overview of combined NERC, MOC-A, & RH Projects

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/epics#79]
# Motivation
Based on notes from the Retrospectives for NERC OpenShift it was concluded that we needed a high-level view of all projects NERC and MOC-A are working on as a way to ensure we can more accurately prioritize.

# Completion criteria
NERC, RH, & MOCA agree that the new chart provides the details they want to know about the high-level information for all three teams and where they intersect.

# Description
- [ ] Provides high-level tasks
- [ ] Provides a way to see the epics associated with those higher-level tasks
- [ ] Provides a way to see the issues associated with those epics
- [ ] Provides an easy way to prioritize high-level tasks
- [ ] Is visible to all of the team members

# References
1. [ZenHub Epic](https://github.com/nerc-project/operations#workspaces/moc-a--rh-sprint-workspace-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTY1NDc2)

# Changelog
2023-11-07: Created Epic Description Tracking Issue
