### ISSUE TITLE
[Epic] MOC Infra OpenShift Cluster

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/epics#82]
# Motivation
We will need to setup a small openshift cluster where we will run containers and VMs for MOC internal services such as Netbox, IPMI gateways, MAAS, etc. This cluster will replace Ovirt.

# Completion criteria
Infra Cluster up and running and usable by MOC team and users.

# Description
- [ ] Hardware
   - [ ] 3x Dell R640s that will act as both controllers and workers (Old OCP-PROD controllers)
      - [ ] Fill each nodes with SSDs for local storage
   - [ ] We have several Dell R440s that we can use as workers should the cluster need to be expanded
- [ ] Storage
   - [ ] Longhorn will be used to use local storage on each controller to act as block/object storage

# References
1. [Epic](https://app.zenhub.com/workspaces/moc-a--rh-sprint-workspace-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTY4NDY2?state=OPEN&state=TODO&state=IN_PROGRESS)

# Changelog
2023-11-28: updated the epic link
