### ISSUE TITLE
[Epic] Design & Implement Spanning Tree Topology for ESI/OCT Network

### ISSUE THREAD

**Issue by joachimweyl** [CCI-MOC/epics#83]
# Motivation
Currently, the spanning tree setup is all one big tree and is somewhat messy. The goal of this epic is to plan how we can redesign the ESI/OCT network to split up the spanning trees and decide what protocols to use based on efficiency and requirements.

# Completion criteria
Spanning Tree Topology for ESI/OCT Network up and running

# Description
- [ ] Design a topology for spanning tree (pick protocol, make figures)
- [ ] Deploy on testing switch to validate
- [ ] Deploy on production switches, schedule downtime

# References
1. [Epic](https://app.zenhub.com/workspaces/moc-a--rh-sprint-workspace-62a210f69d42f600151deae0/epics/Z2lkOi8vcmFwdG9yL1plbmh1YkVwaWMvMTY5NTMy)

# Changelog
2023-12-06: added Epic link
