### ISSUE TITLE
[Epic]

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/epics#87]
# Motivation
To ensure that we have enough storage to replace hardware that is going off warranty and to cover future growth.

# Completion criteria
- [ ] Hardware ordered and installed, 
- [ ] Data migrated to new hardware
- [ ] old hardware deprecated

# Description
To ensure that we have enough storage to replace hardware that is going off warranty and to cover future growth we will use MTC funds to purchase replacement hardware.

# References
1. [document](https://docs.google.com)

# Changelog
2024-02-02: created epic
